/**
 * Declares the workflow-level schemas used to load and pass the author profile
 * through the feedback pipeline.
 */
import { z } from "zod";

import { DOCUMENT_GENRES } from "../../../../../domain/documents/document.constants";

/** Validates the public workflow input accepted by the feedback pipeline. */
export const feedbackWorkflowInputSchema = z.object({
  category: z.string().min(1),
  context: z.string().min(1),
  anchor: z.string().min(1),
  suggestedText: z.string().optional(),
  justification: z
    .string()
    .describe(
      "Original correction justification. Helps the agent distinguish normative issues from intentional stylistic choices.",
    ),
  action: z.enum(["accept", "reject"]),
  severity: z.enum(["high", "medium", "low"]),
  suggestionType: z.enum(["track-change", "comment-only"]),
  comment: z.string().optional(),
  documentUuid: z
    .uuid()
    .describe(
      "Stable document identifier generated by the add-in. The workflow resolves the persisted document profile in the backend.",
    ),
});

export const feedbackDocumentContextSchema = z.object({
  documentId: z.uuid(),
  documentStyleProfileId: z.uuid(),
  documentPreferencesId: z.uuid(),
  documentUuid: z.uuid(),
  defaultGenre: z.enum(DOCUMENT_GENRES),
  processingConfig: z.record(z.string(), z.unknown()),
});

/** Enriches the workflow input with the resolved author profile payload. */
export const feedbackProfileContextSchema = feedbackWorkflowInputSchema.extend({
  authorProfile: z
    .string()
    .describe("Author profile already resolved by the workflow."),
  documentContext: feedbackDocumentContextSchema,
});

/** Reuses the public workflow input as the load-profile step input contract. */
export const loadAuthorProfileInputSchema = feedbackWorkflowInputSchema;
/** Describes the output emitted by the load-profile step. */
export const loadAuthorProfileOutputSchema = feedbackProfileContextSchema;
