/**
 * Declares the workflow-level schemas used to load and pass the author profile
 * through the stylistic correction pipeline.
 */
import { z } from "zod";

import { DOCUMENT_GENRES } from "../../../../../domain/documents/document.constants";

/** Validates the public workflow input accepted by the stylistic pipeline. */
export const stylisticWorkflowInputSchema = z.object({
  text: z.string().describe("Text to correct."),
  documentUuid: z
    .uuid()
    .describe(
      "Stable document identifier generated by the add-in. The workflow resolves the document profile in the backend.",
    ),
  genero: z
    .enum(DOCUMENT_GENRES)
    .default("general")
    .describe("Text genre used to apply genre-specific criteria."),
  title: z
    .string()
    .trim()
    .min(1)
    .optional()
    .describe("Optional document title sent by the add-in."),
  processingConfig: z
    .record(z.string(), z.unknown())
    .optional()
    .describe("Optional document-level processing or batching configuration."),
});

export const stylisticDocumentContextSchema = z.object({
  documentId: z.uuid(),
  documentStyleProfileId: z.uuid(),
  documentPreferencesId: z.uuid(),
  documentUuid: z.uuid(),
  defaultGenre: z.enum(DOCUMENT_GENRES),
  processingConfig: z.record(z.string(), z.unknown()),
});

/** Enriches the workflow input with the resolved author profile payload. */
export const stylisticProfileContextSchema =
  stylisticWorkflowInputSchema.extend({
    authorProfile: z
      .string()
      .describe(
        "Author profile already resolved by the workflow. Required before correction can continue.",
      ),
    authorProfileCorrectionPatternsWordCount: z
      .number()
      .int()
      .nonnegative()
      .describe(
        "Deterministic word count for the ## PATRONES VIVOS section of the profile.",
      ),
    documentContext: stylisticDocumentContextSchema,
  });

/** Reuses the public workflow input as the load-profile step input contract. */
export const loadAuthorProfileInputSchema = stylisticWorkflowInputSchema;
/** Describes the output emitted by the load-profile step. */
export const loadAuthorProfileOutputSchema = stylisticProfileContextSchema;
