import {
  extendZodWithOpenApi,
  OpenApiGeneratorV31,
  OpenAPIRegistry,
} from "@asteasolutions/zod-to-openapi";
import type { OpenAPIV3_1 } from "openapi-types";
import { z } from "zod";

import { DOCUMENT_GENRES } from "../../domain/documents/document.constants";

extendZodWithOpenApi(z);

const RESOLVE_DOCUMENT_CONTEXT_REQUEST_SCHEMA_ID =
  "ResolveDocumentContextRequest";
const RESOLVED_DOCUMENT_CONTEXT_RESPONSE_SCHEMA_ID =
  "ResolvedDocumentContextResponse";
const UNAUTHENTICATED_ERROR_SCHEMA_ID = "UnauthenticatedError";
const INVALID_JSON_BODY_ERROR_SCHEMA_ID = "InvalidJsonBodyError";
const INVALID_DOCUMENT_CONTEXT_REQUEST_ERROR_SCHEMA_ID =
  "InvalidDocumentContextRequestError";

export const resolveDocumentContextRouteRequestSchema = z
  .object({
    documentUuid: z.uuid().meta({
      description:
        "Stable UUID generated by the add-in for the current document.",
    }),
    title: z
      .string()
      .trim()
      .min(1)
      .meta({
        description:
          "Optional document title. When present, it refreshes the persisted title.",
      })
      .optional(),
    genero: z
      .enum(DOCUMENT_GENRES)
      .meta({
        description:
          "Default genre to persist for the document when creating or updating its preferences.",
      })
      .optional(),
    processingConfig: z
      .record(z.string(), z.unknown())
      .meta({
        description:
          "Flexible processing configuration persisted alongside the document preferences.",
      })
      .optional(),
  })
  .strict();

export const resolvedDocumentContextRouteResponseSchema = z
  .object({
    document: z
      .object({
        id: z.uuid(),
        userId: z.string(),
        externalDocumentKey: z.uuid(),
        title: z.string().nullable(),
        lastUsedAt: z.iso.datetime(),
      })
      .strict(),
    preferences: z
      .object({
        id: z.uuid(),
        documentId: z.uuid(),
        defaultGenre: z.enum(DOCUMENT_GENRES),
        processingConfig: z.record(z.string(), z.unknown()),
      })
      .strict(),
    styleProfile: z
      .object({
        id: z.uuid(),
        documentId: z.uuid(),
        profileMarkdown: z.string(),
      })
      .strict(),
  })
  .strict();

export const unauthenticatedRouteErrorSchema = z
  .object({
    error: z.literal("unauthenticated"),
  })
  .strict();

export const invalidJsonBodyRouteErrorSchema = z
  .object({
    error: z.literal("invalid_json_body"),
  })
  .strict();

export const invalidDocumentContextRequestRouteErrorSchema = z
  .object({
    error: z.literal("invalid_document_context_request"),
    issues: z
      .array(
        z.object({}).catchall(z.unknown()).meta({
          description:
            "Zod validation issue describing why the payload was rejected.",
        }),
      )
      .meta({
        description:
          "Zod validation issues describing why the payload was rejected.",
      }),
  })
  .strict();

const documentRouteOpenApiRegistry = new OpenAPIRegistry();

documentRouteOpenApiRegistry.register(
  RESOLVE_DOCUMENT_CONTEXT_REQUEST_SCHEMA_ID,
  resolveDocumentContextRouteRequestSchema,
);

documentRouteOpenApiRegistry.register(
  RESOLVED_DOCUMENT_CONTEXT_RESPONSE_SCHEMA_ID,
  resolvedDocumentContextRouteResponseSchema,
);

documentRouteOpenApiRegistry.register(
  UNAUTHENTICATED_ERROR_SCHEMA_ID,
  unauthenticatedRouteErrorSchema,
);

documentRouteOpenApiRegistry.register(
  INVALID_JSON_BODY_ERROR_SCHEMA_ID,
  invalidJsonBodyRouteErrorSchema,
);

documentRouteOpenApiRegistry.register(
  INVALID_DOCUMENT_CONTEXT_REQUEST_ERROR_SCHEMA_ID,
  invalidDocumentContextRequestRouteErrorSchema,
);

const documentRouteOpenApiGenerator = new OpenApiGeneratorV31(
  documentRouteOpenApiRegistry.definitions,
);

const documentRouteGeneratedSchemas =
  documentRouteOpenApiGenerator.generateComponents().components?.schemas ?? {};

function getGeneratedOpenApiSchema(schemaId: string): OpenAPIV3_1.SchemaObject {
  const schema = documentRouteGeneratedSchemas[schemaId];

  if (!schema || "$ref" in schema) {
    throw new Error(`OpenAPI schema generation failed for ${schemaId}.`);
  }

  return schema as OpenAPIV3_1.SchemaObject;
}

export const resolveDocumentContextRequestOpenApiSchema =
  getGeneratedOpenApiSchema(RESOLVE_DOCUMENT_CONTEXT_REQUEST_SCHEMA_ID);

export const resolvedDocumentContextResponseOpenApiSchema =
  getGeneratedOpenApiSchema(RESOLVED_DOCUMENT_CONTEXT_RESPONSE_SCHEMA_ID);

export const unauthenticatedErrorOpenApiSchema = getGeneratedOpenApiSchema(
  UNAUTHENTICATED_ERROR_SCHEMA_ID,
);

export const invalidJsonBodyErrorOpenApiSchema = getGeneratedOpenApiSchema(
  INVALID_JSON_BODY_ERROR_SCHEMA_ID,
);

export const invalidDocumentContextRequestErrorOpenApiSchema =
  getGeneratedOpenApiSchema(INVALID_DOCUMENT_CONTEXT_REQUEST_ERROR_SCHEMA_ID);
